name: test-workspace

on:
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show current directory
        run: pwd
      - name: Show files (before)
        run: |
          find /home/runner |grep -v cached
      - uses: actions/checkout@v4
      - name: Show files (after checkout)
        run: |
          find /home/runner |grep -v cached
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - name: Show files (after Python)
        run: |
          find /home/runner |grep -v cached
